### ISSUE TITLE
Confusion between STM32WL55 and STM32WLE5

### ISSUE THREAD

**Issue by hpux735** [seeed-lora/LoRa-E5-LoRaWAN-End-Node#2]
I'm struggling with understanding the CPU definition used in this code.  It's pretty clearly using the STM32WL55 in the .ioc file, but the LoRa-E5 uses the STM32WLE5.  Am I missing something?

**Comment by jpmeijers** [comment]
It looks like they generated code for the WL55, and then hacked it by hand to run on the WLE5 :(

@seeedstudio please give us a proper STMCubeIDE example project!

**Comment by danak6jq** [comment]
If you look at the ST firmware package for the STM32WLxx, the examples are all for the STM32WL55 - but, after an admittedly brief look - it appears the WLE5 and WL55 are the same peripherals, the WL55 has an additional CPU core. So, use the single-core LoRaWAN examples and it works on either part.

**Comment by hpux735** [comment]
I ended up using https://github.com/androbi-com/LoRa-E5-Mini-EndNode, and it works great.  This project doesn't work on the new version of CubeMX or CubeIDE.  It's using the old firmware versions.  I'd recommend Seeed merging androbi's repo into here.

**Comment by danak6jq** [comment]
Heh, I did exactly this (I think) last night - use the STM32WLxx example as a starting point, then edit the BSP files (that Cube doesn't touch when regenerating). Thanks for the repo link, will take a look and see how close to the same answer I have.

**Comment by hpux735** [comment]
Yah, that repo really unblocked me.  And the maintainer was responsive and helpful.

**Comment by danak6jq** [comment]
My experimental is different - I used the STM32WLxx example  (as generated with Cube from the V1.1.0 firmware package) for the LoRa_End_Node.

I configured the LoRaWAN middleware to use BSP support, then copied the BSP support as described in the STM32WLxx firmware wad (digging up the reference). The BSP supports the Nucleo board, but you can freely change it as needed, Cube doesn't touch it on regeneration.

The androbi-com repo looks like it started with generating the LoRa application with Cube - which I started to do before realizing the examples already work and I just needed to tweak the BSPs.

Yeah, I'll have to get a repo posted.

**Comment by hpux735** [comment]
Oh, yah.  That makes sense.   I'm using the Seeed E5 module, which moves the console USART port.  I tried using CubeMX to change it, but I never got it to really work.  Androbi's repo has it changed and it works.
