### ISSUE TITLE
Bug in radio_board_if.h confuses

### ISSUE THREAD

**Issue by acutetech** [seeed-lora/LoRa-E5-LoRaWAN-End-Node#3]
Lines 64 & 65 give two definitions of radio capbilities:

#define RBI_CONF_RFO                        RBI_CONF_RFO_LP_HP
#define RBI_CONF_RFO                        RBI_CONF_RFO_HP

This gives a compiler "redefinition" warning.

I attempted to correct this by commenting out the second line. This says "the board supports transmission on both RFO_LP and RFO_HP outputs, switch selectable using radio switch GPIO pins".  This seemed to me a reasonable assumption since RBI_ConfigRFSwitch() includes code for both RBI_SWITCH_RFO_LP and RBI_SWITCH_RFO_HP.

However, what appears to happen is the code selects the RBI_SWITCH_RFO_LP option and the switch settings for this case don't work: the RSSI of uplink messages is extremely poor.

When I comment out the first define it works properly. I believe this means "the board supports transmission on the HP output only, switch selectable using radio switch GPIO pins, and the RBI_SWITCH_RFO_LP code will not be called". 

I would suggest that Seeed corrects the #define error, and also removes code from the RBI_SWITCH_RFO_LP case, which I believe will not be called. As it is, the presence of this code confuses users into thinking the board supports both options.

Of course, it would be so much better if Seeed would publish the schematic. Then engineers can write code confident that their code will drive the hardware correctly.

**Comment by jerryyip** [comment]
Hi @acutetech, LoRa-E5 only supports "high output power" mode, we will make this clear in the wiki, thank you for pointing out the problem!

**Comment by acutetech** [comment]
You say the issue is closed, but you still haven't fixed the bug. As I understand it (can't be sure as I can't see the schematic) line 64 in radio_board_if.h should be commented out: 
//#define RBI_CONF_RFO                        RBI_CONF_RFO_LP_HP
and preferrably the  case RBI_SWITCH_RFO_LP code in radio_board_if.c (lines 169-172) should be replaced by a comment that says LP mode is not supported.

**Comment by jerryyip** [comment]
Already updated. Thanks again @acutetech!
